### ISSUE TITLE
6/12/2024 - Law and AI

### ISSUE THREAD

**Issue by jperiodlangley** [HSV-AI/presentations#46]
# Description:

Andrew is planning to cover:
- A tour through the legal issues raised by AI
  - Personhood/Agency
  - Intellectual Property
    - Authorship
    - Derivative Works
    - Open Source Issues
  - Decisioning
-  Two regulatory schemes
    - Biden executive order
    - AI Act in the European Union
- Deeper dive into IP issues

# Complete the following items to get a presentation ready for Huntsville AI

- [x] Description Completed
- [x] Image Attached
- [x] HSV.AI Event Created - [hsv.ai](https://hsv.ai/events)
- [x] Facebook Event Created - [Facebook Group](https://www.facebook.com/groups/hsvai/)
- [x] LinkedIn Event Created - [Huntsville AI](https://www.linkedin.com/company/huntsville-ai)

# Adding material to the presentations repository

Add the file to present (prefer Jupyter Notebooks or Markdown formated files) to the folder structure. For multiple files, create a directory following the naming convention and add the files to it.

## Naming convention

We use a convention of starting the filenames with a date (year/month/day) so that the files are still sorted by date even when in alphabetical format.

YYMMDD_Session_Description.extension

**Comment by jacquelyneneal** [comment]
I went to a really interesting talk at a Nashville conference that talked about ethics and law implications. Franklin Graves is a lawyer working on how AI products are affected by copyright, trademark, and patent law. I don't know if there are any local lawyers, but it would be cool to get someone in this area to talk to us!

**Comment by jperiodlangley** [comment]
I talked to Andrew Tuggle over the weekend about doing a session for us on Law & AI. Are there any specific areas that were the most interesting? It's probably big enough of a topic that we could have a few sessions a year for this.

**Comment by jacquelyneneal** [comment]
That sounds cool! One thing I'm personally really interested in is related to data ownership for the data many of these models were trained on, especially relating to the European standard of "right to be forgotten", as well as the ownership of these model outputs. I think it's going to be important for both content development and tools/apps built on top of these models.

**Comment by jperiodlangley** [comment]
![law-and-ai](https://github.com/HSV-AI/presentations/assets/6886690/b3e70465-89f1-4504-a739-7e1e2b158071)
