### ISSUE TITLE
MLFlow - open source framework for MLOps

### ISSUE THREAD

**Issue by jperiodlangley** [HSV-AI/presentations#9]
# Suggest a subject for a Huntsville AI presentation

-- PLEASE EDIT HERE

Here's a link to the [website](https://mlflow.org/)

## Info:

MLflow is an open source platform to manage the ML lifecycle, including experimentation, reproducibility, deployment, and a central model registry. 

Looks like it can be hosted or self served.

-- PLEASE STOP EDITING HERE

# Vote for this suggestion

For others in the Huntsville AI community - please +1 this suggestion if it's something you would like to see.

**Comment by Benjamin-Etheredge** [comment]
I can talk on this since I've used it several times. It's a super interesting tool. It will have to be later in the year though as I'm booked through December.
